name: holoviews
dependencies:
  - numpy<1.16.0
  - notebook
  - matplotlib=2.1.2
  - pillow=5.2.0
  - pandas=0.23.4
  - scipy
  - xarray=0.10.9
  - networkx
  - ipython=5.4.1
  - jsonschema=2.6.0
  - cyordereddict
  - nbconvert=5.3.1
  - pyviz::param=1.8.0
  - pyviz::pyviz_comms=0.7.0
  - pyviz::datashader
  - conda-forge::netcdf4=1.3.1
  - conda-forge::ffmpeg
  - conda-forge::flexx=0.4.1
  - conda-forge::plotly=3.4
  - bokeh::bokeh=1.0.0
  - bokeh::selenium
  # Testing requirements
  - flake8
  - nose
  - path.py
  - conda-forge::deepdiff
  - conda-forge::awscli
  - conda-forge::coveralls
  - pip:
    - -e .
